# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title fastLm
#'
#'@param X matric
#'@param y vector
#'@param w vector
#'
#'@export fastLm
#'@return model coefficients
#'@examples
#'fastLm(X,y,w)
NULL

fastLm <- function(X, y, w) {
    .Call(`_blblm_fastLm`, X, y, w)
}

