# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title this is the title
#' Fastlm function in rcpp
#'@param X matrix
#'@param y vector
#'@param w vector
#'@export fastLm
NULL

fastLm <- function(X, y, w) {
    .Call(`_blblm_fastLm`, X, y, w)
}

